/// Flutter icons SettingIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SettingIcon
///      fonts:
///       - asset: fonts/SettingIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SettingIcon {
  SettingIcon._();

  static const _kFontFam = 'SettingIcon';
  static const String? _kFontPkg = null;

  static const IconData preview = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_inverted = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbsup = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
